### ISSUE TITLE
Unable to update PI and contact person in userDB

### ISSUE THREAD

**Issue by mGauder** [qbicsoftware/user-db-portlet#18]
Hi Andreas,

there is a bug in the User Database Projects tab. I tried to change the information of the PI and the contact person, but I am unable to do so. Attached you will find the error message:  ![](https://user-images.githubusercontent.com/9446153/59593420-31975f00-90f2-11e9-9770-946b15a92e15.png) 

Thanks and best,
Marie

**Comment by wow-such-code** [comment]
Has been fixed
